### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by murraybauer** [ezekielchentnik/redux-reporter#3]
How do I use this in Angular 2?  

After NPM install, I add:
`import reporter from './reporter';`

But it says the module is not found.

Also, what is the name of the middleware that I need to include where configuring the store - it is called reporter?
`applyMiddleware(reporter)?`

**Comment by ezekielchentnik** [comment]
@murraybauer apologies for delayed reply.  The readme was not complete.  I've updated documentation.

**Comment by ezekielchentnik** [comment]
@murraybauer does this resolve the issue?  Let me know if you have any more questions related to this issue, I'd be glad to help.
